services:

 #sets up how to make the source data available

 demo:

 tms:

 wms:

   #srs sets the coordinate reference systems as which you want to make your data available. MapProxy reprojects the source data very well to these projections.

   srs: ['EPSG:4326', 'EPSG:3857']

   image_formats: ['image/jpeg', 'image/png']


       transparent: true


  osm_bright_source:

     type: tile

     url: https://geo.timetochange.today/geoserver/gwc/service/tms/1.0.0/osm:osm_bright@EPSG:900913@png/%(z)s/%(x)s/%(y)s.png

     grid: osm_bright_grid_reverse


grids:

 osm_bright_grid:

   base: GLOBAL_MERCATOR

   srs: 'EPSG:3857'

   origin: nw


 osm_bright_grid_reverse:

   base: GLOBAL_MERCATOR

   srs: 'EPSG:3857'

   origin: sw


globals:

 #next are some global configuration options for MapProxy. They mostly explain themselves, or can be looked-up in the MapProxy docs.

 cache:

   # where to store the cached images

   base_dir: './cache_data'

   # where to store lockfiles

   lock_dir: './cache_data/locks'


 # image/transformation options

 image:

     resampling_method: bilinear

     jpeg_quality: 90 

