services:
  #sets up how to make the source data available
  demo:
  tms:
  wms:
    #srs sets the coordinate reference systems as which you want to make your data available. MapProxy reprojects the source data very well to these projections.
    srs: ['EPSG:4326', 'EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']
    md:
      # metadata used in capabilities documents
      title: MapProxy WMS Proxy
      abstract: This is the fantastic MapProxy.
      online_resource: http://mapproxy.org/
      contact:
        person: Majk Shkurti
        position: GIS Developer
        city: Munich

layers:
  #sets up which layers you want to make available using the services above.
  - name: glri_projects
    title: GLRI Projects
    sources: [glri_projects_cache] # This layer should use the glri_projects_cache (defined below) as its source.

caches:
    #sets up how to cache the source data
  glri_projects_cache:
    grids: [osm_grid]
    sources: [glri_projects_source] # Here you set what source data (defined below) you want to cache

sources:
   glri_projects_source:
      type: wms
      supported_formats: [png]
      supported_srs: ['EPSG:3857', 'CRS:84']
      req:
        url: http://crystalball.timetochange.today/geoserver/workspace1/ows
        layers: glri_projects


grids:
  osm_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw 

globals:
  #next are some global configuration options for MapProxy. They mostly explain themselves, or can be looked-up in the MapProxy docs.
  cache:
    # where to store the cached images
    base_dir: './cache_data'
    # where to store lockfiles
    lock_dir: './cache_data/locks'


  # image/transformation options
  image:
      resampling_method: bilinear
      jpeg_quality: 90